[tasks.install]
description = "install with bundler"
run = "bundle"

[tasks.test]
description = "test with RSpec"
depends = ["install"]
run = "bundle exec rspec"

[tasks.lint]
description = "lint with Rubocop"
depends = ["install"]
run = "bundle exec rubocop"

[tasks.demo]
description = "run some ruby"
run = """
    ruby -I lib -e 'require "demo_ruby"; puts "\\033[0;31m#{DemoRuby.run}"'
"""

[tasks."demo:rust-install"]
description = "install cargo-script to run rust as a script"
run = """
cargo install --list | grep cargo-script &> /dev/null \
    || cargo install cargo-script
"""

[tasks."demo:rust"]
depends = ["demo:rust-install"]
description = "say hello from Rust 🦀"
run = """
#!/usr/bin/env run-cargo-script

fn main() {
    println!("Hello Rust 🦀!");
}
"""

[tasks.build]
description = "test, lint and demo all the things"
depends = ["test", "lint", "demo"]

[tasks.clean]
description = "clean up"
run = """
cargo uninstall cargo-script
"""
