# user and repo
user        := `whoami`
current_dir := `basename $( pwd )`

# Colors
RED     := "\\u001b[31m"
GREEN   := "\\u001b[32m"
YELLOW  := "\\u001b[33m"
BLUE    := "\\u001b[34m"
MAGENTA := "\\u001b[35m"
BOLD    := "\\u001b[1m"
RESET   := "\\u001b[0m"

_default:
    @echo "\nHi {{GREEN}}{{user}}!{{RESET}} Welcome to {{RED}}{{current_dir}}{{RESET}}\n"

    @just --list --unsorted

# demo
@demo:
    echo "{{RED}}❌ hi in red{{RESET}}"
    just _announce_rb "✅ hi in green" "{{GREEN}}"
    just _announce_js "🟡 hi in yellow" "{{YELLOW}}"
    just _announce "🔵 hi in blue" "{{BLUE}}"
    just _announce "🟣 hi in magenta" "{{MAGENTA}}"

polyglot: python js perl sh ruby

python:
  #!/usr/bin/env python3
  print('Hello from python!')

js:
  #!/usr/bin/env node
  console.log('Greetings from JavaScript!')

perl:
  #!/usr/bin/env perl
  print "Larry Wall says Hi!\n";

sh:
  #!/usr/bin/env sh
  hello='Yo'
  echo "$hello from a shell script!"

ruby:
  #!/usr/bin/env ruby
  puts "Hello from ruby!"

## Hidden recipies

_bold_squares message:
    @echo -e "{{BOLD}}[{{RESET}}{{message}}{{RESET}}{{BOLD}}]{{RESET}}"

_announce message color:
    #!/usr/bin/env zsh
    echo -e "{{color}}{{message}}{{RESET}}"

_announce_rb message color:
    #!/usr/bin/env ruby
    puts "{{color}}{{message}}{{RESET}}"

_announce_js message color:
    #!/usr/bin/env node
    console.log('{{color}}{{message}}{{RESET}}')
